In [1]:
#p1
smash = ['Mario','DK','Link','Samus','Yoshi','Kirby','Fox','Pikachu']

In [2]:
smash

['Mario', 'DK', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu']

In [3]:
#p2
smash.extend(['Luigi', 'Ness', 'C. Falcon', 'Jigglypuff'])

In [4]:
smash

['Mario',
 'DK',
 'Link',
 'Samus',
 'Yoshi',
 'Kirby',
 'Fox',
 'Pikachu',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff']

In [5]:
#p3
smash.append(['Metal Mario','Polygon Team', 'Master Hand'])

In [6]:
smash

['Mario',
 'DK',
 'Link',
 'Samus',
 'Yoshi',
 'Kirby',
 'Fox',
 'Pikachu',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff',
 ['Metal Mario', 'Polygon Team', 'Master Hand']]

In [7]:
#p4
smash[0:8] = ['Original roster']

In [8]:
smash

['Original roster',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff',
 ['Metal Mario', 'Polygon Team', 'Master Hand']]

In [9]:
#p5
def null_matrix(m,n):
    a = [[0 for _ in range(n)] for _ in range(m)]
    return a

In [10]:
nm = null_matrix(3,4)

In [11]:
nm

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [12]:
#p6
[[['?' for _ in range(2)] for _ in range(3)] for _ in range(4)]

[[['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']]]

In [13]:
#p6
[[['?']*2]*3]*4

[[['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']]]

In [14]:
#p7
mensualidad = {'Disney+' : 7, 'Netflix' : 8.99, 'Prime' : 12.99}

In [15]:
mensualidad

{'Disney+': 7, 'Netflix': 8.99, 'Prime': 12.99}

In [16]:
#p8
del mensualidad['Disney+']
mensualidad['Blim'] = 109
mensualidad['Netflix'] = 139
mensualidad['Prime'] = 99

In [17]:
mensualidad

{'Netflix': 139, 'Prime': 99, 'Blim': 109}

In [18]:
#p9
mensualidad['Tec'] = 20400

In [19]:
mensualidad

{'Netflix': 139, 'Prime': 99, 'Blim': 109, 'Tec': 20400}

In [20]:
#p10
import numpy as np
data = np.array(list(range(1,17))).reshape((4,4))

In [21]:
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
#p11
data[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [23]:
#p12
data[1:4,2:4]

array([[ 7,  8],
       [11, 12],
       [15, 16]])

In [24]:
#p13
features = data[:,:3]
label = data[:,3]

In [25]:
features

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [26]:
label

array([ 4,  8, 12, 16])

In [27]:
#p14
data = [(x,y) for x,y in zip(features,label)]

In [28]:
data

[(array([1, 2, 3]), 4),
 (array([5, 6, 7]), 8),
 (array([ 9, 10, 11]), 12),
 (array([13, 14, 15]), 16)]

In [29]:
#p15
test = data[:int(len(data)*0.25)]
train = data[int(len(data)*0.25):]

In [30]:
train

[(array([5, 6, 7]), 8), (array([ 9, 10, 11]), 12), (array([13, 14, 15]), 16)]

In [31]:
test

[(array([1, 2, 3]), 4)]

#p16

- P(S) = Probabilidad de que a tu amigo le guste smash.
- P(Z) = Probabilidad de que a tu amigo le guste Zelda.

$P(Z|S) = \frac{P(S∩Z)}{P(S)} = \frac{0.35}{0.7} = 0.5 $

#p17

- P(E) = Probabilidad de estar enfermo.
- P(T) = Probabilidad de prueba positiva.

$P(E|T) = \frac{P(T|E)P(E)}{P(T)} = \frac{P(T|E)P(E)}{P(T|E)P(E)+P(T|E´)P(E´)}$

- P(T|E) = 0.99
- P(E) = 0.001
- P(T|E´) = 0.01 
- P(E´) = 0.999

$\frac{(0.99)(0.001)}{(0.99)(0.001)+(0.01)(0.999)} = 0.09016$

P(E|T) = 9.016%

#p18

$\frac{df(x)}{dx} = 3x^2cos(x^2)-2x^4sen(x^2) $

#p19

$\frac{df(x)}{dx} = 4x^3 + x^2cos(x) + 2xsin(x) $

#p20

$\frac{∂f(x,z)}{∂x} = 3x^2 +2xz+z^2 $

$\frac{∂f(x,z)}{∂z} = 3z^2+2xz+x^2 $