1 Crear lista smash

In [1]:
smash=['Mario','DK','Samus','Yoshi','Kirby','Fox','Pikachu']
print(smash)

['Mario', 'DK', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu']


2 Agregar elementos

In [23]:
smash.extend(['Luigi','Ness','C.Falcon','Jigglypuff'])
print(smash)

['Mario', 'DK', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu', 'Luigi', 'Ness', 'C.Falcon', 'Jigglypuff']


3 Agregar lista

In [24]:
smash.append(['Metal Mario','Polygon Team','Master Hand'])
print(smash)

['Mario', 'DK', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu', 'Luigi', 'Ness', 'C.Falcon', 'Jigglypuff', ['Metal Mario', 'Polygon Team', 'Master Hand']]


In [ ]:
4 Reemplazar elementos

In [25]:
temp=smash[7:]
smash=['Original roster']
smash.extend(temp)
print(smash)

['Original roster', 'Luigi', 'Ness', 'C.Falcon', 'Jigglypuff', ['Metal Mario', 'Polygon Team', 'Master Hand']]


Crear funcion null_matrix

In [7]:
def null_matrix(rows,columns):
    f=[];
    for i in range(rows):
        c=[]
        for j in range(columns):
            c.append(0)
        f.append(c)
    return f
a=null_matrix(3,3)
print(a)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


6 Crea una lista de '?'

In [12]:
a=null_matrix(4,3)
r=[]
for i in a:
    rj=[];
    for j in i:
        rj.append(['f','f'])
    r.append(rj)
for i in r:
    print(i)

[['f', 'f'], ['f', 'f'], ['f', 'f']]
[['f', 'f'], ['f', 'f'], ['f', 'f']]
[['f', 'f'], ['f', 'f'], ['f', 'f']]
[['f', 'f'], ['f', 'f'], ['f', 'f']]


7 Crea un diccionario 

In [17]:
mensualidad={'Disney+':7,'Netflix':8.99,'Prime':12.99}
print(mensualidad)

{'Disney+': 7, 'Netflix': 8.99, 'Prime': 12.99}


8 Eliminar y reemplazar

In [18]:
del mensualidad['Disney+']
mensualidad['Blim']=109
mensualidad['Netflix']=139
mensualidad['Prime']=99
print(mensualidad)

{'Netflix': 139, 'Prime': 99, 'Blim': 109}


9 Agregar elemento

In [20]:
mensualidad['Tec']=20400
print(mensualidad)

{'Netflix': 139, 'Prime': 99, 'Blim': 109, 'Tec': 20400}


10 Crear arreglo usando numpy

In [45]:
import numpy as np
raw = np.arange(1,17).reshape(4, 4)
print(raw)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


11 Utilizar slice

In [42]:
raw2=raw[:2,1:3]
print(raw2)

[[2 3]
 [6 7]]


12 Segundo slice

In [43]:
raw3=raw[1:,2:]
print(raw3)

[[ 7  8]
 [11 12]
 [15 16]]


13 Crear 2 arrays

In [68]:
Features=raw[:,:3]
Label=raw[:,3:]
#Label=Label.transpose()
print('Features')
print(Features)
print('Label')
print(Label)

Features
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
Label
[[ 4]
 [ 8]
 [12]
 [16]]


14 Uso de zip

In [75]:
data=[(i,j) for i,j in zip(Features,Label)]
for i in data:
    print(i)

(array([1, 2, 3]), array([4]))
(array([5, 6, 7]), array([8]))
(array([ 9, 10, 11]), array([12]))
(array([13, 14, 15]), array([16]))


15 Dividir lista data

In [2]:
Test=data[0]
Train=data[1:]
print('Test')
print(Test)
print('Train')
print(Train)

NameError: name 'data' is not defined

16.-35% 
17.-0.10%
18.-3x^2cos(x^2)-2x^4sin(x^2) 
19.-2xsin(x)+x^2cos(x)+4x^3 
20.-f'(z)=x^2+2xz+3z^2
    f'(x)=3x^2+2xz+z^2

In [4]:
a=2
a

2

In [7]:
b=3
print(a+b)

5
